Add files via upload

diff --git a/.devcontainer/DockerfileAppBuilderCloud b/.devcontainer/DockerfileAppBuilderCloud
--- a/.devcontainer/DockerfileAppBuilderCloud
+++ b/.devcontainer/DockerfileAppBuilderCloud
@@ -1,11 +1,14 @@
 # Start with Python base image
 FROM python:3.11-slim
 
+ARG GITHUB_TOKEN
+ARG PLUGIN_LIB_TAG
+ARG TAG
 # Set environment variables
 ENV PYTHONUNBUFFERED=1 \
     DEBIAN_FRONTEND=noninteractive \
     PIP_NO_INPUT=1 \
-    NODE_VERSION=18 \
+    NODE_VERSION=20 \
     NEXT_TELEMETRY_DISABLED=1
 
 # Install system dependencies including Node.js
@@ -39,8 +42,11 @@ RUN apt-get update && \
     libxss-dev \
     libasound2 \
     lsof \
+    ripgrep \
+    rsync \
     vim \
     jq \
+    util-linux \
     supervisor && \
     # Install Node.js
     curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - && \
@@ -63,34 +69,42 @@ RUN pip install playwright
 RUN playwright install chromium
 RUN playwright install-deps
 
-RUN curl -fsSL https://code-server.dev/install.sh | sh && \
-    # Install any VS Code extensions you want
-    code-server --install-extension ms-python.python || echo "Failed to install vscode extension"
 
-RUN mkdir -p /root/.config
-COPY .devcontainer/context_params_app_builder.json /root/.config/context_params.json
+RUN curl -fsSL https://code-server.dev/install.sh | sh && \
+   # Install any VS Code extensions you want
+   code-server --install-extension ms-python.python || echo "Failed to install vscode extension"
 
 WORKDIR /app
 
+COPY .devcontainer/entrypoint.sh /entrypoint.sh
 COPY . /app/
-
+RUN rm -rf k8s
 COPY scripts /app/scripts
 
 COPY .devcontainer/supervisord_without_vscode.conf /etc/supervisor/conf.d/supervisord.conf
-
+COPY .devcontainer/supervisord_code_server.conf /etc/supervisor/conf.d/supervisord_code_server.conf
+RUN mkdir -p /root/.config/code-server
+COPY .devcontainer/code_server_config.yaml /root/.config/code-server/config.yaml
+COPY .devcontainer/context_params_app_builder.json /root/.config/context_params.json
+RUN rm .devcontainer/generic_cloud_build.yaml
 RUN rm -rf .git
 
-# Set up working directory for internal-library installations
-WORKDIR /app
-
-# Install dependencies from the new requirements file
-RUN pip install -r requirements.txt
-
-# Remove the new requirements.txt file
-RUN rm /app/requirements.txt
+RUN mkdir -p .emergent
+RUN cat <<EOF > .emergent/emergent.yml
+{
+  "env_image_name": "fastapi_react_mongo_base_image_cloud_arm:${TAG}"
+}
+EOF
 
 # Set up working directory for backend
 WORKDIR /app/backend
+
+RUN python -m venv /root/.venv --system-site-packages
+ENV PATH="/root/.venv/bin:$PATH"
+ENV VIRTUAL_ENV="/root/.venv"
+
+# Configure pip to use extra index URL
+RUN pip config set global.extra-index-url https://d33sy5i8bnduwe.cloudfront.net/simple/
 
 RUN pip install -r requirements.txt
 RUN mkdir -p /app/backend/external_integrations
@@ -105,19 +119,24 @@ RUN npm i -g yarn
 # COPY frontend/package.json frontend/yarn.lock ./
 RUN yarn install
 
-# Install ESLint packages globally
-# RUN npm install -g @eslint/js@9.20.0 eslint@9.20.0 eslint-plugin-react@7.37.4 globals@15.14.0 \
+RUN pip install "git+https://${GITHUB_TOKEN}@github.com/emergentbase/emergent.git@${PLUGIN_LIB_TAG}#subdirectory=plugin_library"
+
+# # Install ESLint packages globally
+# RUN yarn install -g @eslint/js@9.20.0 eslint@9.20.0 eslint-plugin-react@7.37.4 globals@15.14.0 \
 #     eslint-plugin-jsx-a11y@6.8.0 eslint-plugin-import@2.29.1
 
+WORKDIR /app
+RUN git init -b main
+RUN git config --global user.name 'E1' && git config --global user.email 'e1@emergent.sh'
+RUN git add . && git commit --allow-empty -m 'Initial commit'
+RUN git rev-parse HEAD  > /root/.git_init_commit_hash
+
 # Expose ports
-EXPOSE 3000 8001 22 8080 27017
+EXPOSE 3000 8001 22 1111 27017 8010
 EXPOSE 55000-55999
 # Set up entrypoint
 
-RUN eslint --version
-
 WORKDIR /app
+RUN chmod +x /entrypoint.sh
 
-RUN chmod +x .devcontainer/entrypoint.sh
-
-ENTRYPOINT [".devcontainer/entrypoint.sh"]
+ENTRYPOINT ["/entrypoint.sh"]
